#!/usr/bin/env python3
"""Build rules/additional-rules.yml for SecureFlow from RADAR's rules/rule.yml.

The source is a hand-gathered rule set (not fetchable from the Semgrep
registry) plus Snapp's own custom rules. Kept: every rule that Semgrep OSS
can run and that SecureFlow's registry packs do not already contain. Dropped,
each with a reason in the build report:
  custom      Snapp! AppSec custom rules (message says "by Snapp! AppSec")
  sca         Semgrep Supply Chain rules (need the Pro engine)
  dup-self    exact duplicate of an earlier rule in the same file
  dup-pack    exact duplicate of a rule in one of SecureFlow's packs
  invalid     rejected by Semgrep OSS (passed with --invalid)
The community rules the kept rules declare they supersede are listed in the
report too: SecureFlow excludes those from the packs so each issue is
reported once, by the newer rule.

usage: build_additional_rules.py rule.yml packs_dir out.yml report.json [--invalid id,id]
"""
import hashlib, json, os, sys
import yaml

src, packs_dir, out, report = sys.argv[1:5]
invalid = set(sys.argv[sys.argv.index("--invalid") + 1].split(",")) if "--invalid" in sys.argv else set()


def body(r):   # what a rule matches, without its name and wording
    return hashlib.sha1(json.dumps({k: v for k, v in r.items()
                                    if k not in ("id", "message", "metadata", "severity")},
                                   sort_keys=True).encode()).hexdigest()


pack_rules = {}
for fn in sorted(os.listdir(packs_dir)):
    for r in (yaml.safe_load(open(os.path.join(packs_dir, fn))) or {}).get("rules", []):
        pack_rules[r["id"]] = r
pack_bodies = {body(r): rid for rid, r in pack_rules.items()}

kept, dropped, seen, supersedes = [], [], {}, set()
for r in yaml.safe_load(open(src))["rules"]:
    meta = r.get("metadata") or {}
    b = body(r)
    why = None
    if "snapp" in str(r.get("message", "")).lower() and "appsec" in str(r.get("message", "")).lower():
        why = "custom"
    elif meta.get("sca-kind") or "r2c-internal-project-depends-on" in json.dumps(r):
        why = "sca"
    elif b in seen:
        why = "dup-self:" + seen[b]
    elif b in pack_bodies:
        why = "dup-pack:" + pack_bodies[b]
    elif r["id"] in invalid:
        why = "invalid"
    if why:
        dropped.append({"id": r["id"], "why": why}); continue
    seen[b] = r["id"]
    for s in meta.get("supersedes") or []:
        supersedes.add(s.get("rule_id") if isinstance(s, dict) else s)
    kept.append(r)

# Semgrep requires unique ids; the source reuses one id per language variant.
# Repeated ids get the variant's language(s) appended (then a counter if needed).
import collections
count = collections.Counter(r["id"] for r in kept)
taken, renamed = set(), []
for r in kept:
    if count[r["id"]] > 1:
        base = "%s-%s" % (r["id"], "-".join(r.get("languages") or ["any"]))
        new, n = base, 2
        while new in taken or new in pack_rules:
            new, n = "%s-%d" % (base, n), n + 1
        renamed.append({"from": r["id"], "to": new}); r["id"] = new
    taken.add(r["id"])

with open(out, "w") as fh:
    fh.write("# SecureFlow additional rules — generated by rules/build_additional_rules.py\n"
             "# from RADAR's rules/rule.yml (hand-gathered rules; Snapp! AppSec custom rules,\n"
             "# Supply Chain rules and duplicates of the registry packs removed). Do not edit\n"
             "# by hand: rebuild.\n")
    yaml.safe_dump({"rules": kept}, fh, sort_keys=False, allow_unicode=True, width=1000)
json.dump({"kept": len(kept), "dropped": dropped, "renamed": renamed,
           "exclude_from_packs": sorted(s for s in supersedes if s in pack_rules)},
          open(report, "w"), indent=1)
print("kept %d, dropped %d %s" % (len(kept), len(dropped),
      dict(__import__("collections").Counter(d["why"].split(":")[0] for d in dropped))))
print("renamed duplicate ids:", len(renamed))
print("superseded pack rules to exclude:", len([s for s in supersedes if s in pack_rules]))
