name: Infrastructure as Code Scanning

on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'Git repository URL to clone'
        required: true
        type: string

jobs:
  iac-scanning:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the repository
    - name: Clone Repository
      run: |
        git clone https://farsheedify:${{ secrets.GH_TOKEN }}@${{ inputs.repository_url }} repo

    # Step 2: Run KICS Scan
    - name: Run KICS Scan
      run: |
        docker run -t -v "${PWD}/repo":/path -w /path checkmarx/kics scan -p /path --exclude-severities info,low,medium --disable-secrets --ignore-on-exit all --report-formats json -o . --output-name kics-report

    # Step 3: Upload the KICS report as an artifact
    - name: Upload KICS Report to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kics-report
        path: repo/kics-report.json
