name: iac

on:
  workflow_dispatch:  # Allows manual trigger
  workflow_call:  # Allows this workflow to be reusable by other repositories

jobs:
  iac-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install latest Go version
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    # Step 3: Clone and build KICS from source
    - name: Install KICS from source
      run: |
        git clone https://github.com/Checkmarx/kics.git
        cd kics
        go mod vendor
        make build

    # Step 4: run the scan
    - name: Run KICS scan
      run: |
        ls
        cd ..
        ls
        ./kics/binkics scan -q /app/bin/assets/queries -p ${PWD} --exclude-severities info,low --disable-secrets --ignore-on-exit all --report-formats json -o ${PWD} --output-name kics-report -t Ansible,AzureResourceManager,Buildah,CloudFormation,DockerCompose,Dockerfile,GRPC,GoogleDeploymentManager,Kubernetes,Terraform

    # Step 5: Upload the KICS report as an artifact
    - name: Upload KICS report
      uses: actions/upload-artifact@v4
      with:
        name: kics-report
        path: kics-report.json
