name: iac

on:
  workflow_dispatch:  # Allows manual trigger
  workflow_call:  # Allows this workflow to be reusable by other repositories

jobs:
  iac-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: run the scan
    - name: Run KICS scan
      run: |
        docker run -t -v "${PWD}":/path checkmarx/kics scan -p /path --exclude-severities info,low --disable-secrets --ignore-on-exit all --report-formats json -o /path --output-name kics-report -t Ansible,AzureResourceManager,Buildah,CloudFormation,DockerCompose,Dockerfile,GRPC,GoogleDeploymentManager,Kubernetes,Terraform
        
    # Step 3: Upload the KICS report to DefectDojo
    - name: Upload Semgrep json report to Defectdojo
      run: |
        TODAY=$(date +%Y-%m-%d)
        product_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
        curl -X "POST" "https://demo.defectdojo.org/api/v2/reimport-scan/" -H "accept: application/json" -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" -H "Content-Type: multipart/form-data" -F file=@kics-report.json -F "product_type_name=Clubpay" -F "active=true" -F "verified=true" -F "close_old_findings=true" -F "engagement_name=${product_name} (IaC_Scanning)" -F "build_id=${GITHUB_RUN_ID}" -F "minimum_severity=Info" -F "close_old_findings_product_scope=true" -F "scan_date=$TODAY" -F "engagement_end_date=$TODAY" -F "commit_hash=${GITHUB_SHA}" -F "product_name=${product_name}" -F "auto_create_context=true" -F "scan_type=KICS Scan" -F "branch_tag=${GITHUB_REF_NAME}" -F "source_code_management_uri=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
    
    # Step 4: Upload the KICS report as an artifact
    - name: Upload KICS report
      uses: actions/upload-artifact@v4
      with:
        name: kics-report
        path: kics-report.json
