name: Static Application Security Testing

on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'Git repository URL to clone'
        required: true
        type: string

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the Repository
    - name: Clone Repository
      run: |
        git clone https://farsheedify:${{ secrets.GH_TOKEN }}@${{ inputs.repository_url }} repo
        
    # Step 2: Run Semgrep Scan
    - name: Run Semgrep Scan
      run: |
        docker run -e SEMGREP_APP_TOKEN=447264db74cba98b1c2933cd68f65ed5de0bfc6272650d8e51502814ce4bdce8 --rm -v "${PWD}/repo:/src" semgrep/semgrep semgrep scan --json-output=semgrep-report.json    

    # Step 3: Upload the Semgrep Report as an Artifact
    - name: Upload Semgrep Report to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-report
        path: repo/semgrep-report.json
