name: sast

on:
  workflow_dispatch:  # This allows manual trigger
  workflow_call:  # Allows this workflow to be reusable by other repositories
      inputs:
        sast_exclude_list:
          required: false
          type: string # space separated list of files/folders to exclude from scan

jobs:
  sast-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install Semgrep
    - name: Install Semgrep
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install semgrep
    # Step 3: Remove sast_exclude_list
    - name: Remove specified files/directories in sast_exclude_list
      run: |
        for item in ${{ inputs.sast_exclude_list }}; do
          rm -rf $item
        done
    # Step 4: Run Semgrep scan on all files and output to a JSON file
    - name: Run Semgrep scan
      run: |
        semgrep scan --metrics=off --severity=WARNING --severity=ERROR --exclude=*.yml --exclude=*.yaml --exclude=*.json --exclude=*docker* --exclude=*Docker* --config=p/nodejsscan --config=p/owasp-top-ten --config=p/cwe-top-25 --config=p/security-audit --config=p/default --json-output=semgrep-report.json

    # Step 5: Upload the Semgrep report to DefectDojo
    - name: Upload Semgrep json report to Defectdojo
      run: |
        TODAY=$(date +%Y-%m-%d)
        product_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
        curl -X "POST" "https://demo.defectdojo.org/api/v2/reimport-scan/" -H "accept: application/json" -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" -H "Content-Type: multipart/form-data" -F file=@semgrep-report.json -F "product_type_name=clubpay" -F "active=true" -F "verified=true" -F "close_old_findings=true" -F "engagement_name=${product_name}(SAST)" -F "build_id=${GITHUB_RUN_ID}" -F "minimum_severity=Info" -F "close_old_findings_product_scope=true" -F "scan_date=$TODAY" -F "engagement_end_date=$TODAY" -F "commit_hash=${GITHUB_SHA}" -F "product_name=${product_name}" -F "auto_create_context=true" -F "scan_type=Semgrep JSON Report" -F "tags=${GITHUB_REF_NAME}" -F "source_code_management_uri=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
        
    # Step 6: Upload the Semgrep report as an artifact
    - name: Upload Semgrep report
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-report
        path: semgrep-report.json
