name: Static Application Security Testing

on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'Git repository URL to clone'
        required: true
        type: string

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the Repository
    - name: Clone Repository
      run: |
        git clone https://farsheedify:${{ secrets.GH_TOKEN }}@${{ inputs.repository_url }} repo
        
    # Step 2: Run Semgrep Scan
    - name: Run Semgrep Scan
      run: |
        docker run --rm -v "${PWD}:/src" semgrep/semgrep semgrep ci --metrics=off --exclude=*.yml --exclude=*.yaml --exclude=*.json --exclude=*docker* --exclude=*Docker* --config=p/mobsfscan --config=p/nodejsscan --config=p/owasp-top-ten --config=p/cwe-top-25 --config=p/security-audit --config=p/default --gitlab-sast --output=semgrep-report.json || EXIT_CODE=$?
        if [ $EXIT_CODE -ne 0 ] && [ $EXIT_CODE -ne 1 ]; then exit $EXIT_CODE; fi    

    # Step 3: Upload the Semgrep Report as an Artifact
    - name: Upload Semgrep Report to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-report
        path: repo/semgrep-report.json
