name: sca

on:
  workflow_dispatch:  # This allows manual trigger
  workflow_call:  # Allows this workflow to be reusable by other repositories

jobs:
  syft-grype-scan:
    runs-on: ubuntu-latest

    steps:
# Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

# Step 2: Install Syft and Grype
    - name: Install Syft and Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
# Step 3: Generate SBOM using Syft
    - name: Generate SBOM
      run: |
        /usr/local/bin/syft version
        /usr/local/bin/syft . -v -o json > sbom.json

# Step 4: Scan SBOM using Grype
    - name: Scan SBOM with Grype
      run: |
        /usr/local/bin/grype version
        /usr/local/bin/grype sbom:sbom.json -v -o json > grype-report.json

# Step 5: Upload the Grype report as an artifact
    - name: Upload Grype report
      uses: actions/upload-artifact@v4
      with:
        name: grype-report
        path: grype-report.json
