name: Secret Detection

on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'Git repository URL to clone'
        required: true
        type: string

jobs:
  secret-detection:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the Repository
    - name: Clone Repository
      run: |
        git clone https://farsheedify:${{ secrets.GH_TOKEN }}@${{ inputs.repository_url }} repo

    # Step 2: Run Gitleaks Scan
    - name: Run Gitleaks Scan
      run: |
        docker run -v ${PWD}/repo:/path -w /path zricethezav/gitleaks:latest dir --exit-code 0 --report-path gitleaks-report.json .

    # Step 3: Upload the Gitleaks Report as an Artifact
    - name: Upload Gitleaks Report to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: repo/gitleaks-report.json
